require ("prototypes.entity.concrete-wall")
require ("prototypes.entity.plastic-wall")
require ("prototypes.entity.powered-wall")
require ("prototypes.entity.composite-wall")
require ("prototypes.entity.iron-cable")
require ("prototypes.entity.barbed-wire")
require ("prototypes.entity.razor-wire")
require ("prototypes.entity.electric-fence")
